// ==============================================================================
// Generated Managed Bindings for MidnightGate
// Generated by Compact Compiler (compactc) v0.20+
// Target: Midnight Preprod / Preview Network
// ==============================================================================

export interface LedgerState {
  verified_nullifiers: Set<string>;
  total_verified_investors: bigint;
  default_threshold_usd: bigint;
  authority_id: string;
}

export interface PrivateWitnesses {
  user_asset_value: bigint;
  user_secret_salt: string;
}

export interface CircuitProofInputs {
  required_threshold: bigint;
  context_nonce: string;
}

export interface VerificationReceipt {
  nullifier: string;
  txHash: string;
  blockHeight: number;
  verifiedAt: number;
  status: 'PROVEN_AND_REGISTERED' | 'REJECTED';
}

export const CONTRACT_CIRCUITS = [
  'verify_and_register_credential',
  'update_default_threshold'
] as const;

export const DEFAULT_PREPROD_CONTRACT_ADDRESS = 'midnight1contract7qxg39e0x2k8w94hf6v7d8s9a0b1c2d3e4f5';
