// ==============================================================================
// Generated Managed Bindings for MidnightGate
// Generated by Compact Compiler (compactc) v0.20+
// Target: Midnight Preprod / Preview Network
// ==============================================================================

export interface LedgerState {
  verified_nullifiers: Set<string>;
  total_verified_investors: bigint;
  default_threshold_usd: bigint;
  authority_id: string;
}

export interface PrivateWitnesses {
  user_asset_value: bigint;
  user_secret_salt: string;
}

export interface CircuitProofInputs {
  required_threshold: bigint;
  context_nonce: string;
}

export interface VerificationReceipt {
  nullifier: string;
  txHash: string;
  blockHeight: number;
  verifiedAt: number;
  status: 'PROVEN_AND_REGISTERED' | 'REJECTED';
}

export const CONTRACT_CIRCUITS = [
  'verify_and_register_credential',
  'update_default_threshold'
] as const;

// Midnight Preprod Bech32m Contract Identifier
export const DEFAULT_PREPROD_CONTRACT_ADDRESS = 'mn_contract_preprod1qq48m5x9d2a3y7k4h8v7c2d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3';
export const DEFAULT_PREPROD_CONTRACT_HEX = '02005a7d3b84f18e9a263d90cb15e3479a861d3f9b208dc750a92e105e4b986a7d';
